### ISSUE TITLE
Crash when downloading or using anything of the tools menu

### ISSUE THREAD

**Issue by Amilton78** [Xpl0itU/WiiUDownloader#76]
Hi! When I try to do any of those things it crashes with:
```
Could not load a pixbuf from /org/gtk/libgtk/theme/Adwaita/assets/check-symbolic.svg.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../gtk/gtkiconhelper.c:495:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /run/current-system/sw/share/icons/breeze-dark/status/16/image-missing.svg: Unable to load image-loading module: libpixbufloader-svg.so: libpixbufloader-svg.so: cannot open shared object file: No such file or directory (gdk-pixbuf-error-quark, 5)
Bail out! Gtk:ERROR:../gtk/gtkiconhelper.c:495:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /run/current-system/sw/share/icons/breeze-dark/status/16/image-missing.svg: Unable to load image-loading module: libpixbufloader-svg.so: libpixbufloader-svg.so: cannot open shared object file: No such file or directory (gdk-pixbuf-error-quark, 5)
SIGABRT: abort
PC=0x7fb81c5a6a8c m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x73eb80, 0xc0002fc1c0)
	/usr/local/go/src/runtime/cgocall.go:157 +0x4b fp=0xc0002fc198 sp=0xc0002fc160 pc=0x48ac6b
github.com/Xpl0itU/dialog._Cfunc_filedlg(0x1ab0d40, 0x0, 0x2, 0x1ab0d60)
	_cgo_gotypes.go:228 +0x4c fp=0xc0002fc1c0 sp=0xc0002fc198 pc=0x700b8c
github.com/Xpl0itU/dialog.chooseFile({0x854653?, 0xc0002ed7e8?}, {0x852802, 0x4}, 0x156288?, 0xc0002fc4c0)
	/root/go/pkg/mod/github.com/!xpl0it!u/dialog@v0.0.0-20230805114139-ec888310aded/dlgs_linux.go:84 +0x14a fp=0xc0002fc490 sp=0xc0002fc1c0 pc=0x7017ea
github.com/Xpl0itU/dialog.(*DirectoryBuilder).browse(...)
	/root/go/pkg/mod/github.com/!xpl0it!u/dialog@v0.0.0-20230805114139-ec888310aded/dlgs_linux.go:120
github.com/Xpl0itU/dialog.(*DirectoryBuilder).Browse(0x0?)
	/root/go/pkg/mod/github.com/!xpl0it!u/dialog@v0.0.0-20230805114139-ec888310aded/dlgs.go:146 +0x65 fp=0xc0002fc518 sp=0xc0002fc490 pc=0x7009a5
main.(*MainWindow).ShowAll.func1()
	/project/cmd/WiiUDownloader/mainwindow.go:208 +0xbf fp=0xc0002fc580 sp=0xc0002fc518 pc=0x71a8df
runtime.call16(0xc0000c6c90, 0xc0001560f0, 0x0, 0x0, 0x0, 0x0, 0xc0002fcad0)
	/usr/local/go/src/runtime/asm_amd64.s:747 +0x43 fp=0xc0002fc5a0 sp=0xc0002fc580 pc=0x4ebf23
runtime.reflectcall(0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	<autogenerated>:1 +0x36 fp=0xc0002fc5e0 sp=0xc0002fc5a0 pc=0x4f01b6
reflect.Value.call({0x7741e0?, 0xc0001560f0?, 0x0?}, {0x85282e, 0x4}, {0xb57ea0, 0x0, 0x78d7e0?})
	/usr/local/go/src/reflect/value.go:596 +0xce7 fp=0xc0002fcbf0 sp=0xc0002fc5e0 pc=0x510867
reflect.Value.Call({0x7741e0?, 0xc0001560f0?, 0x179f580?}, {0xb57ea0?, 0xc0000061a0?, 0xc0000ead08?})
	/usr/local/go/src/reflect/value.go:380 +0xb9 fp=0xc0002fcc68 sp=0xc0002fcbf0 pc=0x50fab9
github.com/gotk3/gotk3/glib.goMarshal(0x5?, 0x0, 0x1, 0x7ffdf497f3a0, 0x4?, 0x14c1cd0?)
	/root/go/pkg/mod/github.com/gotk3/gotk3@v0.6.2/glib/glib.go:271 +0xa11 fp=0xc0002fcf18 sp=0xc0002fcc68 pc=0x6c80f1
_cgoexp_b565b27e8aff_goMarshal(0x0?)
	_cgo_gotypes.go:6411 +0x2c fp=0xc0002fcf58 sp=0xc0002fcf18 pc=0x6cc5ec
runtime.cgocallbackg1(0x6cc5c0, 0x4c655c?, 0x0)
	/usr/local/go/src/runtime/cgocall.go:329 +0x2c2 fp=0xc0002fd028 sp=0xc0002fcf58 pc=0x48b162
runtime.cgocallbackg(0x4c655c?, 0xc0000061a0?, 0x300000002?)
	/usr/local/go/src/runtime/cgocall.go:245 +0x109 fp=0xc0002fd0b8 sp=0xc0002fd028 pc=0x48ae09
runtime.cgocallbackg(0x6cc5c0, 0x7ffdf497f190, 0x0)
	<autogenerated>:1 +0x29 fp=0xc0002fd0e0 sp=0xc0002fd0b8 pc=0x4efdc9
runtime.cgocallback(0xc0002fd140, 0x48ac95, 0x72cc40)
	/usr/local/go/src/runtime/asm_amd64.s:1035 +0xcc fp=0xc0002fd108 sp=0xc0002fd0e0 pc=0x4ed76c
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:474 +0x8 fp=0xc0002fd118 sp=0xc0002fd108 pc=0x4eb9e8
runtime.cgocall(0x72cc40, 0xc0002fd178)
	/usr/local/go/src/runtime/cgocall.go:175 +0x75 fp=0xc0002fd150 sp=0xc0002fd118 pc=0x48ac95
github.com/gotk3/gotk3/gtk._Cfunc_gtk_main()
	_cgo_gotypes.go:17490 +0x3f fp=0xc0002fd178 sp=0xc0002fd150 pc=0x6d619f
github.com/gotk3/gotk3/gtk.Main(...)
	/root/go/pkg/mod/github.com/gotk3/gotk3@v0.6.2/gtk/gtk.go:1242
main.main.func1()
	/project/cmd/WiiUDownloader/main.go:47 +0x7f fp=0xc0002fd1c8 sp=0xc0002fd178 pc=0x714d7f
runtime.call16(0xc0000c6c90, 0xc000012120, 0x0, 0x0, 0x0, 0x0, 0xc0002fd718)
	/usr/local/go/src/runtime/asm_amd64.s:747 +0x43 fp=0xc0002fd1e8 sp=0xc0002fd1c8 pc=0x4ebf23
runtime.reflectcall(0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	<autogenerated>:1 +0x36 fp=0xc0002fd228 sp=0xc0002fd1e8 pc=0x4f01b6
reflect.Value.call({0x7741e0?, 0xc000012120?, 0x5026d1?}, {0x85282e, 0x4}, {0xb57ea0, 0x0, 0xb27d20?})
	/usr/local/go/src/reflect/value.go:596 +0xce7 fp=0xc0002fd838 sp=0xc0002fd228 pc=0x510867
reflect.Value.Call({0x7741e0?, 0xc000012120?, 0x13cb560?}, {0xb57ea0?, 0x4f761c?, 0x8?})
	/usr/local/go/src/reflect/value.go:380 +0xb9 fp=0xc0002fd8b0 sp=0xc0002fd838 pc=0x50fab9
github.com/gotk3/gotk3/glib.goMarshal(0x49b5c8?, 0x0, 0x1, 0x7ffdf497fee0, 0xc0000ebbe8?, 0x493805?)
	/root/go/pkg/mod/github.com/gotk3/gotk3@v0.6.2/glib/glib.go:271 +0xa11 fp=0xc0002fdb60 sp=0xc0002fd8b0 pc=0x6c80f1
_cgoexp_b565b27e8aff_goMarshal(0x30?)
	_cgo_gotypes.go:6411 +0x2c fp=0xc0002fdba0 sp=0xc0002fdb60 pc=0x6cc5ec
runtime.cgocallbackg1(0x6cc5c0, 0xc0000ebcc0?, 0x0)
	/usr/local/go/src/runtime/cgocall.go:329 +0x2c2 fp=0xc0002fdc70 sp=0xc0002fdba0 pc=0x48b162
runtime.cgocallbackg(0x4c655c?, 0xc0000061a0?, 0x300000002?)
	/usr/local/go/src/runtime/cgocall.go:245 +0x109 fp=0xc0002fdd00 sp=0xc0002fdc70 pc=0x48ae09
runtime.cgocallbackg(0x6cc5c0, 0x7ffdf497fcd0, 0x0)
	<autogenerated>:1 +0x29 fp=0xc0002fdd28 sp=0xc0002fdd00 pc=0x4efdc9
runtime.cgocallback(0xc0002fdd88, 0x48ac95, 0x71f7b0)
	/usr/local/go/src/runtime/asm_amd64.s:1035 +0xcc fp=0xc0002fdd50 sp=0xc0002fdd28 pc=0x4ed76c
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:474 +0x8 fp=0xc0002fdd60 sp=0xc0002fdd50 pc=0x4eb9e8
runtime.cgocall(0x71f7b0, 0xc0002fddc0)
	/usr/local/go/src/runtime/cgocall.go:175 +0x75 fp=0xc0002fdd98 sp=0xc0002fdd60 pc=0x48ac95
github.com/gotk3/gotk3/glib._Cfunc_g_application_run(0x13c9a60, 0x0, 0x13c8f40)
	_cgo_gotypes.go:1568 +0x4b fp=0xc0002fddc0 sp=0xc0002fdd98 pc=0x6c390b
github.com/gotk3/gotk3/glib.(*Application).Run.func4(0xc000000000?, {0x0?, 0x0, 0x6dd415?}, 0x12?)
	/root/go/pkg/mod/github.com/gotk3/gotk3@v0.6.2/glib/application.go:185 +0x74 fp=0xc0002fde00 sp=0xc0002fddc0 pc=0x6c6574
github.com/gotk3/gotk3/glib.(*Application).Run(0x85d554?, {0x0?, 0x0, 0x0})
	/root/go/pkg/mod/github.com/gotk3/gotk3@v0.6.2/glib/application.go:185 +0x1b9 fp=0xc0002fded0 sp=0xc0002fde00 pc=0x6c6499
main.main()
	/project/cmd/WiiUDownloader/main.go:49 +0x14c fp=0xc0002fdf40 sp=0xc0002fded0 pc=0x714c6c
runtime.main()
	/usr/local/go/src/runtime/proc.go:267 +0x2bb fp=0xc0002fdfe0 sp=0xc0002fdf40 pc=0x4bec1b
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0002fdfe8 sp=0xc0002fdfe0 pc=0x4ed9c1

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc000086fa8 sp=0xc000086f88 pc=0x4bf06e
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:404
runtime.forcegchelper()
	/usr/local/go/src/runtime/proc.go:322 +0xb3 fp=0xc000086fe0 sp=0xc000086fa8 pc=0x4beef3
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000086fe8 sp=0xc000086fe0 pc=0x4ed9c1
created by runtime.init.6 in goroutine 1
	/usr/local/go/src/runtime/proc.go:310 +0x1a

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc000087778 sp=0xc000087758 pc=0x4bf06e
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:404
runtime.bgsweep(0x0?)
	/usr/local/go/src/runtime/mgcsweep.go:280 +0x94 fp=0xc0000877c8 sp=0xc000087778 pc=0x4aaff4
runtime.gcenable.func1()
	/usr/local/go/src/runtime/mgc.go:200 +0x25 fp=0xc0000877e0 sp=0xc0000877c8 pc=0x4a0185
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000877e8 sp=0xc0000877e0 pc=0x4ed9c1
created by runtime.gcenable in goroutine 1
	/usr/local/go/src/runtime/mgc.go:200 +0x66

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc00002a150?, 0x8d0090?, 0x1?, 0x0?, 0xc0000071e0?)
	/usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc000087f70 sp=0xc000087f50 pc=0x4bf06e
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:404
runtime.(*scavengerState).park(0xb28320)
	/usr/local/go/src/runtime/mgcscavenge.go:425 +0x49 fp=0xc000087fa0 sp=0xc000087f70 pc=0x4a8889
runtime.bgscavenge(0x0?)
	/usr/local/go/src/runtime/mgcscavenge.go:653 +0x3c fp=0xc000087fc8 sp=0xc000087fa0 pc=0x4a8e1c
runtime.gcenable.func2()
	/usr/local/go/src/runtime/mgc.go:201 +0x25 fp=0xc000087fe0 sp=0xc000087fc8 pc=0x4a0125
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000087fe8 sp=0xc000087fe0 pc=0x4ed9c1
created by runtime.gcenable in goroutine 1
	/usr/local/go/src/runtime/mgc.go:201 +0xa5

goroutine 5 [finalizer wait]:
runtime.gopark(0x801c20?, 0x1004c0201?, 0x0?, 0x0?, 0x4c7225?)
	/usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc000086628 sp=0xc000086608 pc=0x4bf06e
runtime.runfinq()
	/usr/local/go/src/runtime/mfinal.go:193 +0x107 fp=0xc0000867e0 sp=0xc000086628 pc=0x49f207
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000867e8 sp=0xc0000867e0 pc=0x4ed9c1
created by runtime.createfing in goroutine 1
	/usr/local/go/src/runtime/mfinal.go:163 +0x3d

rax    0x0
rbx    0x3e1e
rcx    0x7fb81c5a6a8c
rdx    0x6
rdi    0x3e1e
rsi    0x3e1e
rbp    0x7fb81b136a80
rsp    0x7ffdf497cba0
r8     0x7
r9     0x1b07f90
r10    0x8
r11    0x246
r12    0x7fb81d4d4da0
r13    0x6
r14    0x7ffdf497ccb0
r15    0x7fb81ce4c1b0
rip    0x7fb81c5a6a8c
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
```

Running with sudo at least gets me to the file picker, but it still crashes after selecting some place
Forgot to mention, I'm on Linux, NixOS

**Comment by Xpl0itU** [comment]
Fixed by the user
